log4r_config:
  loggers:
    - name: info_logger
      trace: "false"
      outputters:
        - stderr
        - info
  outputters:
    - type: StdoutOutputter
      name: stderr
      level: DEBUG
      formatter:
        date_pattern: "%Y-%m-%d %H:%M:%S"
        pattern: "(%d) [%l] %m"
        type: PatternFormatter

    - type: FileOutputter
      name: info
      level: INFO
      date_pattern: "%Y%m%d"
      trunc: "false"
      filename: "#{HOME}/info.log"
      formatter:
        date_pattern: "%Y-%m-%d %H:%M:%S"
        pattern: "(%d) [%l] %m"
        type: PatternFormatter
